config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :trains
  resources :timetables
  resources :stations
  resources :users
  root 'stations#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/station.rb
class Station < ApplicationRecord
has_many :timetables

end

app/controllers/stations_controller.rb
class StationsController < ApplicationController
  before_action :set_station, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource
  # GET /stations
  # GET /stations.json
  def index
    @stations = Station.all
  end

  # GET /stations/1
  # GET /stations/1.json
  def show
  end

  # GET /stations/new
  def new
    @station = Station.new
  end

  # GET /stations/1/edit
  def edit
  end

  # POST /stations
  # POST /stations.json
  def create
    @station = Station.new(station_params)

    respond_to do |format|
      if @station.save
        format.html { redirect_to @station, notice: 'Station was successfully created.' }
        format.json { render :show, status: :created, location: @station }
      else
        format.html { render :new }
        format.json { render json: @station.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stations/1
  # PATCH/PUT /stations/1.json
  def update
    respond_to do |format|
      if @station.update(station_params)
        format.html { redirect_to @station, notice: 'Station was successfully updated.' }
        format.json { render :show, status: :ok, location: @station }
      else
        format.html { render :edit }
        format.json { render json: @station.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stations/1
  # DELETE /stations/1.json
  def destroy
    @station.destroy
    respond_to do |format|
      format.html { redirect_to stations_url, notice: 'Station was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_station
      @station = Station.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def station_params
      params.require(:station).permit(:address, :phone,:name)
    end
end

app/helpers/stations_helper.rb
module StationsHelper
end

app/views/stations/_form.html.erb
<%= form_with(model: station, local: true) do |form| %>
  <% if station.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(station.errors.count, "error") %> prohibited this station from being saved:</h2>

      <ul>
      <% station.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_field :address, id: :station_adress %>
  </div>
    <div class="field">
      <%= form.label :name %>
      <%= form.text_field :name, id: :station_adress %>
    </div>

  <div class="field">
    <%= form.label :phone %>
    <%= form.text_field :phone, id: :station_phone %>
  </div>


  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/stations/edit.html.erb
<h1>Editing Station</h1>

<%= render 'form', station: @station %>

<%= link_to 'Show', @station %> |
<%= link_to 'Back', stations_path %>

app/views/stations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Stations</h1>

<table id="attributes">
  <thead>
  <tr>
    <th>Name</th>
    <th>Address</th>
    <th>Phone</th>
    <th>Timetable</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @stations.each do |station| %>
      <tr>

        <td><%= station.name %></td>
        <td><%= station.address %></td>
        <td><%= station.phone %></td>

        </td>
        <td><%= link_to 'Show', station %></td>
        <% if current_user &&current_user.role=="admin" %>
            <td><%= link_to 'Edit', edit_station_path(station) %></td>
            <td><%= link_to 'Destroy', station, method: :delete, data: {confirm: 'Are you sure?'} %></td>
        <% end %>
      </tr>
  <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Station', new_station_path  if current_user &&current_user.role=="admin"  %>

app/views/stations/new.html.erb
<h1>New Station</h1>

<%= render 'form', station: @station %>

<%= link_to 'Back', stations_path %>

app/views/stations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Address:</strong>
  <%= @station.address %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @station.phone %>
</p>

<p>
  <strong>Timetable:</strong>

<table id="attributes">
  <thead>
  <tr>
    <th>Name</th>
    <th>Arrival Time</th>
    <th>Departure Time</th>
    <th>Trains</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @station.timetables.each do |table| %>
      <tr>
        <td><%= table.name %></td>
        <td><%= table.arrival_time.strftime('%Y-%m-%d %H-%M-%S') %></td>
        <td><%= table.departure_time.strftime('%Y-%m-%d %H-%M-%S') %></td>

        <td>
          <ul>
            <% table.trains.each do |train| %>
                <li><%= train.name %></li>
            <% end %>
          </ul>
        </td>


      </tr>
  <% end %>
  </tbody>
</table>

<br>
</p>

<% if current_user and  current_user.role=="admin"%>
     <%= link_to 'Edit', edit_station_path(@station) %> |
<%= link_to 'Back', stations_path %>
<% end%>