config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :trains
  resources :timetables
  resources :stations
  resources :users
  root 'stations#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/timetables_controller.rb
class TimetablesController < ApplicationController
  before_action :set_timetable, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource
  # GET /timetables
  # GET /timetables.json
  def index
    @timetables = Timetable.all
  end

  # GET /timetables/1
  # GET /timetables/1.json
  def show
  end

  # GET /timetables/new
  def new
    @timetable = Timetable.new
  end

  # GET /timetables/1/edit
  def edit
  end

  # POST /timetables
  # POST /timetables.json
  def create
    @timetable = Timetable.new(timetable_params)
    respond_to do |format|
      if @timetable.save
        format.html { redirect_to @timetable, notice: 'Timetable was successfully created.' }
        format.json { render :show, status: :created, location: @timetable }
      else
        format.html { render :new }
        format.json { render json: @timetable.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /timetables/1
  # PATCH/PUT /timetables/1.json
  def update
    respond_to do |format|
      if @timetable.update(timetable_params)
        format.html { redirect_to @timetable, notice: 'Timetable was successfully updated.' }
        format.json { render :show, status: :ok, location: @timetable }
      else
        format.html { render :edit }
        format.json { render json: @timetable.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /timetables/1
  # DELETE /timetables/1.json
  def destroy
    @timetable.destroy
    respond_to do |format|
      format.html { redirect_to timetables_url, notice: 'Timetable was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_timetable
      @timetable = Timetable.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def timetable_params
      params.require(:timetable).permit(:arrival_time, :departure_time, :station_id, :name)
    end
end

app/helpers/timetables_helper.rb
module TimetablesHelper
end

app/views/timetables/_form.html.erb
<%= form_with(model: timetable, local: true) do |form| %>
  <% if timetable.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(timetable.errors.count, "error") %> prohibited this timetable from being saved:</h2>

      <ul>
      <% timetable.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
    <div class="field">
      <%= form.label :name %>
      <%= form.text_field :name %>
    </div>

  <div class="field">
    <%= form.label :arrival_time %>
    <%= form.datetime_select :arrival_time, :as => :datetime_picker %>
  </div>

  <div class="field">
    <%= form.label :departure_time %>
    <%= form.datetime_select :departure_time,:as => :datetime_picker %>
  </div>


    <div class="field">
      <%= form.label :station_id %>
      <%= form.select :station_id , Station.all.collect { |s| [s.name, s.id] } %>

    </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/timetables/edit.html.erb
<h1>Editing Timetable</h1>

<%= render 'form', timetable: @timetable %>

<%= link_to 'Show', @timetable %> |
<%= link_to 'Back', timetables_path %>

app/views/timetables/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Timetables</h1>

<table id="attributes">
  <thead>
    <tr>
      <th>Arrival time</th>
      <th>Departure time</th>
      <th>Station</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @timetables.each do |timetable| %>
      <tr>
        <td><%= timetable.arrival_time %></td>
        <td><%= timetable.departure_time %></td>
        <td><%= timetable.station.name %></td>
        <td><%= link_to 'Show', timetable %></td>
        <td><%= link_to 'Edit', edit_timetable_path(timetable) %></td>
        <td><%= link_to 'Destroy', timetable, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Timetable', new_timetable_path %>

app/views/timetables/new.html.erb
<h1>New Timetable</h1>

<%= render 'form', timetable: @timetable %>

<%= link_to 'Back', timetables_path %>

app/views/timetables/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Arrival time:</strong>
  <%= @timetable.arrival_time %>
</p>

<p>
  <strong>Departure time:</strong>
  <%= @timetable.departure_time %>
</p>

<p>
  <strong>Station:</strong>
  <%= @timetable.station.name %>
</p>

<%= link_to 'Edit', edit_timetable_path(@timetable) %> |
<%= link_to 'Back', timetables_path %>